"""empty message

Revision ID: 07757638bd2d
Revises: ee09fa98bab1
Create Date: 2020-11-23 18:09:29.252596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07757638bd2d'
down_revision = 'ee09fa98bab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_like_date'), 'likes', ['like_date'], unique=False)
    op.drop_table('association_table_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table_likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='association_table_likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_table_likes_user_id_fkey')
    )
    op.drop_index(op.f('ix_likes_like_date'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
